import Head from 'next/head';
import { ReactNode } from 'react';
import { useMediaQuery } from 'react-responsive';
import Navbar from './navbar/navbar';
import MobileNavBar from './navbar/mobileNavBar';

type LayoutProps = {
  children: ReactNode;
  title: string;
};

export default function layout({ children, title }: LayoutProps) {
  const isDesktop = useMediaQuery({ query: '(min-width: 768px)' });
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {isDesktop ? (
        <div className='flex h-screen'>
          <Navbar />
          <main className='main-content flex-1 overflow-y-auto'>
            {children}
          </main>
        </div>
      ) : (
        <>
          <MobileNavBar />
          <div className='flex h-screen'>
            <main className='main-content flex-1 overflow-y-auto'>
              {children}
            </main>
          </div>
        </>
      )}
    </>
  );
}
