import Head from 'next/head';
import { ReactNode } from 'react';
import Navbar from './navbar/navbar';

type LayoutProps = {
  children: ReactNode;
  title: string;
};

export default function layout({ children, title }: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex h-screen'>
        <Navbar />
        <main className='main-content flex-1 overflow-y-auto'>{children}</main>
      </div>
    </>
  );
}
